competition/urls.py
from django.conf.urls import url
from . import views

app_name = 'competition'


urlpatterns = [
    #LEAGUE URLS
    #index /competition
    url(r'^$', views.index, name='index'),

    # PLAYERS URLS
    #players /competition/player
    url(r'^player/$', views.player, name='player'),
    # players /competition/player/8/
    url(r'^player/(?P<player_id>[0-9]+)/$', views.player_details, name='player_details'),
    # players /competition/player/delete/8/
    url(r'^player/(?P<player_id>[0-9]+)/delete/$', views.player_delete, name='player_delete'),
    # players /competition/player/update/8/
    url(r'^player/(?P<player_id>[0-9]+)/update/$', views.player_update, name='player_update'),
    # player /competition/player/add
    url(r'^player/add/$', views.player_add, name='player-add'),


    # LEAGUES URLS
    # competition/8
    url(r'^league/(?P<league_id>[0-9]+)/$', views.league_details, name='league_details'),
    #competition/league/add/
    url(r'^league/add/$', views.league_add, name='league-add'),
    #competition/league/8/update/
    url(r'^league/(?P<league_id>[0-9]+)/update/$', views.league_update, name='league_update'),
    #competition/league/8/delete/
    url(r'^league/(?P<league_id>[0-9]+)/delete/$', views.league_delete, name='league_delete'),
    #competition/league/8/seasons
    url(r'^league/(?P<league_id>[0-9]+)/seasons/$', views.league_seasons, name='league_seasons'),

    url(r'^league/(?P<league_id>[0-9]+)/seasons/(?P<season_id>[0-9]+)/$', views.season_table, name='season_table'),

    url(r'^league/(?P<league_id>[0-9]+)/seasons/add$', views.season_add, name='season_add'),
    # competition/ekstraklasa/2/teams
    #url(r'^league/(?P<league_name>.+)/(?P<league_id>[0-9]+)/$', views.season_teams, name='season_teams'),
    # url(r'^league/(?P<league_name>.+)/(?P<season_id>[0-9]+)/teams$', views.league_seasons, name='league_season_teams'),

    # TEAM URLS
    # /competition/team
    url(r'^team/$', views.team, name='team'),
    #competition/team/8
    url(r'^team/(?P<team_id>[0-9]+)/$', views.team_details, name='team_details'),
    # /competition/team/add
    url(r'^team/add/$', views.team_add, name='team-add'),
    # /competition/team/delete/8/
    url(r'^team/(?P<team_id>[0-9]+)/delete/$', views.team_delete, name='team_delete'),
    # /competition/team/update/8/
    url(r'^team/(?P<team_id>[0-9]+)/update/$', views.team_update, name='team_update'),

    # MATCH URLS
    url(r'^match/$', views.match, name='match'),
    url(r'^match/(?P<match_id>[0-9]+)/$', views.match_details, name='match_details'),
    url(r'^match/add/$', views.match_add, name='match-add'),
    url(r'^match/(?P<match_id>[0-9]+)/update/$', views.match_update, name='match_update'),
    url(r'^match/(?P<match_id>[0-9]+)/delete/$', views.match_delete, name='match_delete'),

    # MATCH FACTS URLS
    url(r'match/(?P<match_id>[0-9]+)/fact/add/$', views.fact_add, name='fact_add'),
    url(r'match/(?P<match_id>[0-9]+)/fact/(?P<fact_id>[0-9]+)/update/$', views.fact_update, name='fact_update'),
    url(r'match/(?P<match_id>[0-9]+)/fact/(?P<fact_id>[0-9]+)/delete/$', views.fact_delete, name='fact_delete'),

    #TABELA
    #url(r'table/(?P<league_id>[0-9]+)/(?P<league_name>.+)/$', views.league_table, name='league_table'),

]

players_dot_com/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^competition/', include('competition.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

competition/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from datetime import datetime



class LeagueType(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Season(models.Model):
    league = models.ForeignKey(LeagueType, on_delete=models.CASCADE)
    season = models.CharField(max_length=20)

    def __str__(self):
        return "{} {}".format(self.league, self.season)


class Team(models.Model):
    name = models.CharField(max_length=20)
    league = models.ManyToManyField(LeagueType)
    avatar = models.ImageField(upload_to='media/avatars')

    @classmethod
    def create(cls, name):
        team = cls(name=name)
        return team

    def __str__(self):
        return self.name


class Kolejka(models.Model):
    name = models.CharField(max_length=2)
    league = models.ForeignKey(LeagueType, on_delete=models.CASCADE, blank=True, null=True)

    @classmethod
    def create(cls, name, season):
        kolejka = cls(name=name, league=season)
        return kolejka

    def __str__(self):
        return "{}-{}".format(self.name, self.league)


class Match(models.Model):
    host = models.ForeignKey(Team, related_name='matches_as_host', on_delete=models.CASCADE)
    guest = models.ForeignKey(Team, related_name='MatchGuest', on_delete=models.CASCADE)
    kolejka = models.ForeignKey(Kolejka, on_delete=models.CASCADE, blank=True, null=True)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.now().strftime("%Y-%m-%d"), blank=True, null=True)  # data moze byc null
    hostGoals = models.IntegerField(validators=[MinValueValidator(0)], blank=True, null=True)  # gole nie moga byc na minus, moze byc null
    guestGoals = models.IntegerField(validators=[MinValueValidator(0)], blank=True, null=True) # gole nie moga byc na minus, moze byc null

    @classmethod
    def create(cls, host, guest, league):
        match = cls(host=host, guest=guest, league=league)

        return match

    def __str__(self):
        return "{} {} : {} {}  {}".format(self.host, self.hostGoals, self.guestGoals, self.guest, self.date)


class Table(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    league = models.ForeignKey(LeagueType, on_delete=models.CASCADE)
    points = models.PositiveIntegerField(validators=[MinValueValidator(0)], default=0) # nie mozna miec ujemnych pkt

    @classmethod
    def create(cls, team, league, points):
        table = cls(team=team, league=league, points=points)
        return table

    def __str__(self):
        return "{}-{}-{}".format(self.team, self.league, self.points)


class Player(models.Model):
    name = models.CharField(max_length=100)
    sname = models.CharField(max_length=100)
    age = models.PositiveIntegerField(validators=[MinValueValidator(1)]) # minimalny wiek gracza
    team = models.ForeignKey(Team) # TODO not req

    def __str__(self):
        return "{}-{}-{}-{}".format(self.name, self.sname, self.age, self.team)


class MatchFacts(models.Model):
    INCIDENT_TYPE = (
        ('none', 'none'),
        ('goal', 'goal'),
        ('sub in', 'sub in'),
        ('sub out', 'sub out'),
        ('yellow card', 'yellow card'),
        ('red card', 'red card'),
    )
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    incident = models.CharField(max_length=15,
                                choices=INCIDENT_TYPE,
                                default='none')
    minute = models.PositiveIntegerField(validators=[MinValueValidator(0), MaxValueValidator(120)]) # mecz trwa max 120 min

    def __str__(self):
        return "{}-{}-{}-{}".format(self.match, self.player, self.incident, self.minute)


class TeamStats(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    goalsScored = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    goalsLost = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    matchesWon = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    matchesLost = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    matchesDraw = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    scores = models.IntegerField(validators=[MinValueValidator(0)], default=0)

    @classmethod
    def create(cls, team, season):
        teamStats = cls(team=team, season=season)
        return teamStats


    def addPoints(self, points, update):
        if update:
            self.scores += points
            value = 1
        else:
            self.scores -= points
            value = -1

        if points == 3:
            self.matchesWon += value
        elif points == 1:
            self.matchesDraw += value
        else:
            self.matchesLost += value


    def addScoredGoals(self, goals, update):
        if update:
            self.goalsScored += goals
        else:
            self.goalsScored -= goals

    def addLostGoals(self, goals, update):
        if update:
            self.goalsLost += goals
        else:
            self.goalsLost -=goals

    def __str__(self):
        return "{} {}".format(self.team, self.season)


class PlayerStats(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    season = models.ForeignKey(Season, on_delete=models.CASCADE)
    goalsScored = models.IntegerField(validators=[MinValueValidator(0)], default=0)

    @classmethod
    def create(cls, player, season, goalsScored):
        playerStats = cls(player=player, season=season, goalsScored=goalsScored)
        return playerStats


    def addScoredGoals(self, goals, update):
        if update:
            self.goalsScored += goals
        else:
            self.goalsScored -= goals

competition/forms.py
from .models import Player, Season
from django import forms
from .models import Team, LeagueType, Match, MatchFacts


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['name', 'sname', 'age', 'team']
        labels = {
            'name': 'Imie',
            'sname': 'Nazwisko',
            'age': 'Wiek',
            'team': 'Druzyna'
        }


class TeamForm(forms.ModelForm):

    name = forms.CharField(max_length=100)
    league = forms.ModelMultipleChoiceField(queryset=LeagueType.objects.all(), widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Team

        fields = ['avatar', 'name', 'league']
        labels = {
            'avatar': 'Avatar',
            'name': 'Nazwa',
            'league': 'Liga',
        }


class LeagueForm(forms.ModelForm):
    class Meta:
        model = LeagueType
        fields = ['name']
        labels = {
            'name': 'Nazwa',
        }


class SeasonForm(forms.ModelForm):
    class Meta:
        model = Season
        fields = ['season']
        labels  = {
            'season': 'Season',
        }


class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ['season', 'host', 'guest', 'date', 'hostGoals', 'guestGoals', 'kolejka',]
        labels = {
            'season': 'League',
            'host': 'Gospodarz',
            'guest': 'Gosc',
            'date': 'Data',
            'hostGoals': 'Gole gospodarze',
            'guestGoals': 'Gole goscie',
            'kolejka': 'kolejka'
        }


class MatchFactForm(forms.ModelForm):
    class Meta:
        model = MatchFacts
        fields = ('match', 'player', 'incident', 'minute')
        labels = {
            'match': 'Mecz',
            'player': 'Gracz',
            'incident': 'Zdarzenie',
            'minute': 'Minuta',
        }

competition/templates/competition/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <script src="https://use.fontawesome.com/1598e5e6aa.js"></script>

    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>{%  block title %}Best League{% endblock %}</title>
    <style>
        {% block style %}
        {% endblock %}
    </style>

    {% include 'competition/bootstrap_css.html' %}

</head>
<body>

{% include 'competition/navbar.html' %}

<div class="container" style="text-align: center;">
    {%  block body %}
    {% endblock %}
</div>

</body>
</html>

competition/templates/competition/fact_add.html
{% extends 'competition/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-4 col-sm-offset-4" style="text-align: left;">
        <form action="" method="post" >
            {{ fact_form|crispy }}
            {% csrf_token %}
            <div style="text-align:center;">
                <input class="btn btn-lg btn-primary" type="submit" name="submit" value="Zapisz" />
            </div>
        </form>
    </div>
</div>

{% endblock %}

competition/templates/competition/index.html
{% extends 'competition/base.html' %}
{% load staticfiles %}

{%  block body %}

    <div class="row">
        <div class="col-sm-7">
            <h1>Ligi</h1>

        </div>
        <div class="col-sm-5">
            <a href="{% url 'competition:league-add'  %}">
                <button type="button" class="btn btn-default">Add League</button>
            </a>
        </div>
    </div>
    <br>
    {% if all_league %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            {% for league in all_league %}
                    <div class="col-sm-6" style="height: 80px;">
                        <h1 class="title"><a href="{% url 'competition:league_details' league.id %}">{{ league.name }}</a></h1>
                    </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
        <h3>Niema Ligi do wyswietlenia </h3>
    {% endif %}
{% endblock %}

competition/templates/competition/league_add.html
{% extends 'competition/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-4 col-sm-offset-4" style="text-align: left;">
        <form action="" method="post" >
            {{ league_form|crispy }}
            {% csrf_token %}
            <div style="text-align:center;">
                <input class="btn btn-lg btn-primary" type="submit" name="submit" value="Zapisz" />
            </div>
        </form>
    </div>
</div>

{% endblock %}

competition/templates/competition/league_detail.html
{% extends 'competition/base.html' %}

{% block body %}
<div class="row">
    <div class="col-sm-8">
        <h1> {{ league.name }}</h1>
    </div>
    <div class="col-sm-4">
        <a href="{% url 'competition:league_update' league.id %}"><button class="btn btn-default" type="button">Edit</button></a>
        <a href="{% url 'competition:league_delete' league.id %}"><button class="btn btn-default" type="button">Delete</span></button></a>
    </div>
</div>

<hr/>

<div class="row">
    <div class="col-sm-6 col-md-offset-3">
        {% if teams %}
            {% for team in teams %}
                    <img style="width: 80px; height: 80px;" src="{{ team.avatar.url }}" />
                    <div class="info" style="height: 80px;">
                        <h2 style="vertical-align: middle;"><a href="{% url 'competition:team_details' team.id %}">{{ team.name }}</a></h2>
                    </div>
            {% endfor %}
        {% else %}
            <h2>There is not teams in this league</h2>
        {% endif %}
    </div>
</div>
{% endblock %}

competition/templates/competition/league_seasons.html
{% extends 'competition/base.html' %}

{% block body %}

<a href="{% url 'competition:season_add' league.id %}">
    <button type="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Season</button>
</a>

    <h2>{{ league.name }}</h2>

    {% if seasons %}
        {% for s in seasons %}
            <li>
                <a href="{% url 'competition:season_table' league.id s.id %}"> {{ s.season }} </a>
            </li>
            <br>
        {% endfor %}
    {% else %}
        <h2>No seasons found.</h2>
    {% endif %}

{% endblock %}

competition/templates/competition/match.html
{% extends 'competition/base.html' %}

{% block style %}
{{ block.super }}

table {
    margin: 20px auto;
    border-spacing: 5px 12px;
}

.team-host
{
    padding: 10px;
    padding-right: 200px;
}

.team-guest
{
    padding: 10px;
    padding-left: 200px;
}

.match
{
    background-color: rgb(255, 255, 255);
    padding: 0px;
    margin: 0px 0px 20px;
}

img
{
    width: 100%;
    width: 50px;
    height: 50px;
    padding: 0px;
    margin: 0px;
}

{% endblock %}

{% block body %}

<div class="row">
<a href="{% url 'competition:match-add'  %}">
    <button class="btn btn-default" type="button">Add match</button>
</a>
</div>

<div class="row">
    <div class="col-md-8 col-sm-offset-2">
{% if matches %}

    <table>
    {% for match in matches %}
        <tr class="match">
            <td class="team-host">
                <a class="team-link pull-left" href="{% url 'competition:team_details' match.host.id %}">{{ match.host.name }}</a>
            </td>
            <td>
                <a href="{% url 'competition:match_details' match.id %}">
                    <b  style="font-size: 20px;">{{ match.hostGoals }} : {{ match.guestGoals }}</b>
                </a>
            </td>
            <td class="team-guest">
                <a class="team-link pull-right" href="{% url 'competition:team_details' match.guest.id %}">{{ match.guest.name }}</a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <h2>No matches found.</h2>
{% endif %}
        </div>
</div>
{% endblock %}

competition/templates/competition/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'competition:index' %}">Best League</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse"  id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'competition:index' %}">
                        <span class="glyphicon glyphicon-knight" aria-hidden="true"></span>&nbsp; Rozgrywki</a>
                </li>
                <li class=""><a href="{% url 'competition:team' %}">
                    <span class="glyphicon glyphicon-bookmark" aria-hidden="true"></span>&nbsp; Druzyny</a>
                </li>
                <li class=""><a href="{% url 'competition:player' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Pilkarze</a>
                </li>
                <li class=""><a href="{% url 'competition:match' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Mecze</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

competition/templates/competition/player.html
{% extends 'competition/base.html' %}

{%  block body %}

    <div class="row">
        <div class="col-sm-7">
            <h1>Pilkarze</h1>
        </div>
        <div class="col-sm-5">
            <a href="{% url 'competition:player-add'  %}">
                <button type="button" class="btn btn-default">Dodaj pilkarza</button>
            </a>
        </div>


    </div>


    {% if all_players %}
    <ul>

            <br>
            {% for player in all_players %}
                <li>
                    <a href="{% url 'competition:player_details' player.id  %}"> {{ player.name }} {{ player.sname }}</a>
                    <a href="{% url 'competition:player_update' player.id %}"><button type="button" class="btn btn-default">Edit</button></a>
                    <a href="{% url 'competition:player_delete' player.id %}"><button type="button" class="btn btn-default">Delete</button></a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>Niema pilkarzy do wyswietlenia </h3>
    {% endif %}
{% endblock %}

competition/templates/competition/season_add.html
{% extends 'competition/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-4 col-sm-offset-4" style="text-align: left;">
        <form action="" method="post" >
            {{ season_form|crispy }}
            {% csrf_token %}
            <div style="text-align:center;">
                <input class="btn btn-lg btn-primary" type="submit" name="submit" value="Zapisz" />
            </div>
        </form>
    </div>
</div>

{% endblock %}

competition/templates/competition/season_table.html
{% extends 'competition/base.html' %}

{% block style %}
{{ block.super }}

{% endblock %}

{% block body %}

    {% if team_stats %}
    <div class="row" style="text-align: initial;">
        <h1> {{ season.league.name }} {{ season.season }}</h1>
        <br>

        <table class="points_table">
            <thead>
                <tr>
					<th class="col-xs-1">#</th>
					<th class="col-xs-5">Team</th>
					<th class="col-xs-1">Won</th>
					<th class="col-xs-1">Lost</th>
                    <th class="col-xs-1">Draw</th>
					<th class="col-xs-2">Goals</th>
					<th class="col-xs-1">Points</th>
				</tr>
            </thead>
            <tbody class="points_table_scrollbar">
                {% for stats in team_stats %}
                    {% if forloop.counter|divisibleby:2 %}
                    <tr class="even">
                    {% else %}
                    <tr class="odd">
                    {% endif %}
                        <td class="col-xs-1">
                            {{ forloop.counter }}
                        </td>
                        <td class="col-xs-5">
                            <a href="{% url 'competition:team_details' stats.team.id %}">{{ stats.team.name }}</a>
                        </td>
                        <td class="col-xs-1">
                            {{ stats.matchesWon }}
                        </td>
                        <td class="col-xs-1">
                            {{ stats.matchesLost }}
                        </td>
                        <td class="col-xs-1">
                            {{ stats.matchesDraw }}
                        </td>
                        <td class="col-xs-2">
                            {{ stats.goalsScored }}/{{ stats.goalsLost}}
                        </td>
                        <td class="col-xs-1">
                            {{ stats.scores }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
    {% else %}
        <h2>No info found.</h2>
    {% endif %}

    {% if stats %}
            <div class="row" style="text-align: initial;">
                <h1>Top Scorer</h1>
                <table class="points_table">
                    <thead>
                        <tr>
                            <th class="col-xs-1">#</th>
                            <th class="col-xs-5">Player</th>
                            <th class="col-xs-4">Team</th>
                            <th class="col-xs-2">Goals</th>
                        </tr>
                    </thead>
                    <tbody class="points_table_scrollbar">
                        {% for s in stats %}
                            {% if forloop.counter|divisibleby:2 %}
                            <tr class="even">
                            {% else %}
                            <tr class="odd">
                            {% endif %}
                                <td class="col-xs-1">
                                    {{ forloop.counter }}
                                </td>
                                <td class="col-xs-5">
                                    <a href="{% url 'competition:player_details' s.player.id %}">{{ s.player.name }} {{ s.player.sname }}</a>
                                </td>
                                <td class="col-xs-4">
                                    {{ s.player.team.name }}
                                </td>
                                <td class="col-xs-2">
                                    {{ s.goalsScored }}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
    {% endif %}
{% endblock %}

competition/templates/competition/season_teams.html
{% extends 'competition/base.html' %}

{% block body %}

    {% if teams %}

        <div class="container-fluid">
            <div class=”row”>
                <div class="col-md-12" style="background-color: #BBBBCC"> <h1 class="navbar-brand" style="font-size: x-large">{{ league_name }}</h1> </div>
            </div>
        </div>

        <div class="container-fluid" >
            <nav class="navbar navbar-default" style="background-color: #CCCCCC">
                <div class="conteiner-fluid" >
                    <div>
                        <ul class="nav navbar-nav">
                            <li><a href="{% url 'competition:league_table' league_id league_name %}" style="color: #000000"> <h3>Sprawdz Tabela<h3> </a></li>
                            {% for t in teams %}
                                <li><a href="{% url 'competition:team_details' t.id  %}"> <h3>{{ t.name }}</h3> </a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
             </nav>
        </div>


    {% else %}
        <h2>No Teams found.</h2>
    {% endif %}

    <div class="container-fluid">
        <div class=”row”>
           <div class="col-md-12" style="background-color: #CCCDDD">

           </div>
        </div>
    </div>

    {% if  kolejka_list %}
        <div class="col-md-5">
            <div class="container-fluid">
                <table class="table table-hover">
                     <thead>
                        <tr>
                            <div class="col-md-2">
                                <th>Gospodarz</th>
                            </div>
                            <th></th>
                            <th></th>
                            <th>Goscie</th>
                            <th>Edytuj</th>
                        </tr>
                     </thead>
                     <tbody>
                        {% for k_list in  kolejka_list %}
                                <td>{{ league_name }} kolejka {{ k_list.name }}</td>
                            {%  for match in k_list.match_set.all %}
                                <tr>
                                    <td>
                                        <a href="{% url 'competition:match_details' match.id  %}">
                                            {{ match.host }}

                                        </a>
                                    </td>
                                    <td>
                                        {% if match.hostGoals != null %}
                                                {{ match.hostGoals }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if match.guestGoals != null %}
                                                {{ match.guestGoals }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="{% url 'competition:match_details' match.id  %}">

                                            {{ match.guest }}
                                        </a>

                                    </td>
                                   <td>
                                        <a href="{% url 'competition:match_update' match.id %}"><button type="button"><span class="glyphicon glyphicon-edit"></span></button></a>
                                        <br>
                                   </td>

                                </tr>
                            {%  endfor %}
                        {% endfor %}
                     </tbody>
                </table>
            </div>
        </div>
    {% else %}
        <h2>No kolejka found.</h2>
    {% endif %}
{% endblock %}

competition/templates/competition/team.html
{% extends 'competition/base.html' %}

{%  block body %}

<div class="row">
    <div class="col-sm-8">
        <h1>Teams</h1>
    </div>
    <div class="col-sm-4">
        <a href="{% url 'competition:team-add'  %}">
            <button type="button" class="btn btn-default">Add Team</button>
        </a>
    </div>

</div>
<hr/>
<div class="row">
    <div class="col-sm-12 ">
        {% if all_teams %}
            <div class="row">
                {% for team in all_teams %}
                    <div class="col-sm-4">
                        <img style="width: 80px; height: 80px;" src="{{ team.avatar.url }}" />
                        <div class="info" style="height: 80px;">
                            <h2 style="vertical-align: middle;"><a href="{% url 'competition:team_details' team.id %}">{{ team.name }}</a></h2>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h2>There is not teams in this league</h2>
        {% endif %}
    </div>
</div>



{% endblock %}

competition/templates/competition/team_add.html
{% extends 'competition/base.html' %}
{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-4 col-sm-offset-4" style="text-align: left;">
        <form action="" method="post" enctype="multipart/form-data">
            {{ team_form|crispy }}
            {% csrf_token %}
            <div style="text-align:center;">
                <input class="btn btn-lg btn-primary" type="submit" name="submit" value="Zapisz" />
            </div>
        </form>
    </div>
</div>

{% endblock %}